/*
	ArduinoProMicro ports : 
		PORTB :            *,       [D15],       [D16],       [D14],        [D8],        [D9],       [D10],           *
		PORTC :            *,           *,           *,           *,           *,           *,        [D5],           *
		PORTD :         [D3],        [D2],       [RX0],       [TX0],        [D4],           *,           *,        [D6]
		PORTE :            *,           *,           *,           *,           *,           *,        [D7],           *
		PORTF :            *,           *,           *,           *,        [A3],        [A2],        [A1],        [A0]
*/

#ifndef ARDUINO_PRO_MICRO_PINMAP_H
#define ARDUINO_PRO_MICRO_PINMAP_H

	#if defined(__AVR_ATmega32U4__)

		#define FE_DIGITAL_PIN_D7_MASK B01000000
		#define FE_DIGITAL_PIN_D7_PORT_MODE DDRE
		#define FE_DIGITAL_PIN_D7_PORT_IN PINE
		#define FE_DIGITAL_PIN_D7_PORT_OUT PORTE
		#define FE_DIGITAL_PIN_D7_PORT_NUMBER 4

		#define FE_DIGITAL_PIN_D15_MASK B00000010
		#define FE_DIGITAL_PIN_D15_PORT_MODE DDRB
		#define FE_DIGITAL_PIN_D15_PORT_IN PINB
		#define FE_DIGITAL_PIN_D15_PORT_OUT PORTB
		#define FE_DIGITAL_PIN_D15_PORT_NUMBER 1
		#define FE_INTERRUPT_PIN_D15_GROUP_MASK B00000001
		#define FE_INTERRUPT_PIN_D15_GROUP PCMSK0
		#define FE_INTERRUPT_PIN_D15_GROUP_NUMBER 0
		#define FE_INTERRUPT_PIN_D15_MASK B00000010

		#define FE_DIGITAL_PIN_D16_MASK B00000100
		#define FE_DIGITAL_PIN_D16_PORT_MODE DDRB
		#define FE_DIGITAL_PIN_D16_PORT_IN PINB
		#define FE_DIGITAL_PIN_D16_PORT_OUT PORTB
		#define FE_DIGITAL_PIN_D16_PORT_NUMBER 1
		#define FE_INTERRUPT_PIN_D16_GROUP_MASK B00000001
		#define FE_INTERRUPT_PIN_D16_GROUP PCMSK0
		#define FE_INTERRUPT_PIN_D16_GROUP_NUMBER 0
		#define FE_INTERRUPT_PIN_D16_MASK B00000100

		#define FE_DIGITAL_PIN_D14_MASK B00001000
		#define FE_DIGITAL_PIN_D14_PORT_MODE DDRB
		#define FE_DIGITAL_PIN_D14_PORT_IN PINB
		#define FE_DIGITAL_PIN_D14_PORT_OUT PORTB
		#define FE_DIGITAL_PIN_D14_PORT_NUMBER 1
		#define FE_INTERRUPT_PIN_D14_GROUP_MASK B00000001
		#define FE_INTERRUPT_PIN_D14_GROUP PCMSK0
		#define FE_INTERRUPT_PIN_D14_GROUP_NUMBER 0
		#define FE_INTERRUPT_PIN_D14_MASK B00001000

		#define FE_DIGITAL_PIN_D3_MASK B00000001
		#define FE_DIGITAL_PIN_D3_PORT_MODE DDRD
		#define FE_DIGITAL_PIN_D3_PORT_IN PIND
		#define FE_DIGITAL_PIN_D3_PORT_OUT PORTD
		#define FE_DIGITAL_PIN_D3_PORT_NUMBER 3

		#define FE_DIGITAL_PIN_D2_MASK B00000010
		#define FE_DIGITAL_PIN_D2_PORT_MODE DDRD
		#define FE_DIGITAL_PIN_D2_PORT_IN PIND
		#define FE_DIGITAL_PIN_D2_PORT_OUT PORTD
		#define FE_DIGITAL_PIN_D2_PORT_NUMBER 3

		#define FE_DIGITAL_PIN_RX0_MASK B00000100
		#define FE_DIGITAL_PIN_RX0_PORT_MODE DDRD
		#define FE_DIGITAL_PIN_RX0_PORT_IN PIND
		#define FE_DIGITAL_PIN_RX0_PORT_OUT PORTD
		#define FE_DIGITAL_PIN_RX0_PORT_NUMBER 3

		#define FE_DIGITAL_PIN_TX0_MASK B00001000
		#define FE_DIGITAL_PIN_TX0_PORT_MODE DDRD
		#define FE_DIGITAL_PIN_TX0_PORT_IN PIND
		#define FE_DIGITAL_PIN_TX0_PORT_OUT PORTD
		#define FE_DIGITAL_PIN_TX0_PORT_NUMBER 3

		#define FE_DIGITAL_PIN_D4_MASK B00010000
		#define FE_DIGITAL_PIN_D4_PORT_MODE DDRD
		#define FE_DIGITAL_PIN_D4_PORT_IN PIND
		#define FE_DIGITAL_PIN_D4_PORT_OUT PORTD
		#define FE_DIGITAL_PIN_D4_PORT_NUMBER 3
		#define FE_ANALOG_PIN_D4_MASK B00100000

		#define FE_DIGITAL_PIN_D6_MASK B10000000
		#define FE_DIGITAL_PIN_D6_PORT_MODE DDRD
		#define FE_DIGITAL_PIN_D6_PORT_IN PIND
		#define FE_DIGITAL_PIN_D6_PORT_OUT PORTD
		#define FE_DIGITAL_PIN_D6_PORT_NUMBER 3
		#define FE_ANALOG_PIN_D6_MASK B00100010

		#define FE_DIGITAL_PIN_D8_MASK B00010000
		#define FE_DIGITAL_PIN_D8_PORT_MODE DDRB
		#define FE_DIGITAL_PIN_D8_PORT_IN PINB
		#define FE_DIGITAL_PIN_D8_PORT_OUT PORTB
		#define FE_DIGITAL_PIN_D8_PORT_NUMBER 1
		#define FE_ANALOG_PIN_D8_MASK B00100011
		#define FE_INTERRUPT_PIN_D8_GROUP_MASK B00000001
		#define FE_INTERRUPT_PIN_D8_GROUP PCMSK0
		#define FE_INTERRUPT_PIN_D8_GROUP_NUMBER 0
		#define FE_INTERRUPT_PIN_D8_MASK B00010000

		#define FE_DIGITAL_PIN_D9_MASK B00100000
		#define FE_DIGITAL_PIN_D9_PORT_MODE DDRB
		#define FE_DIGITAL_PIN_D9_PORT_IN PINB
		#define FE_DIGITAL_PIN_D9_PORT_OUT PORTB
		#define FE_DIGITAL_PIN_D9_PORT_NUMBER 1
		#define FE_ANALOG_PIN_D9_MASK B00100100
		#define FE_INTERRUPT_PIN_D9_GROUP_MASK B00000001
		#define FE_INTERRUPT_PIN_D9_GROUP PCMSK0
		#define FE_INTERRUPT_PIN_D9_GROUP_NUMBER 0
		#define FE_INTERRUPT_PIN_D9_MASK B00100000

		#define FE_DIGITAL_PIN_D10_MASK B01000000
		#define FE_DIGITAL_PIN_D10_PORT_MODE DDRB
		#define FE_DIGITAL_PIN_D10_PORT_IN PINB
		#define FE_DIGITAL_PIN_D10_PORT_OUT PORTB
		#define FE_DIGITAL_PIN_D10_PORT_NUMBER 1
		#define FE_ANALOG_PIN_D10_MASK B00100101
		#define FE_INTERRUPT_PIN_D10_GROUP_MASK B00000001
		#define FE_INTERRUPT_PIN_D10_GROUP PCMSK0
		#define FE_INTERRUPT_PIN_D10_GROUP_NUMBER 0
		#define FE_INTERRUPT_PIN_D10_MASK B01000000

		#define FE_DIGITAL_PIN_D5_MASK B01000000
		#define FE_DIGITAL_PIN_D5_PORT_MODE DDRC
		#define FE_DIGITAL_PIN_D5_PORT_IN PINC
		#define FE_DIGITAL_PIN_D5_PORT_OUT PORTC
		#define FE_DIGITAL_PIN_D5_PORT_NUMBER 2

		#define FE_DIGITAL_PIN_A0_MASK B10000000
		#define FE_DIGITAL_PIN_A0_PORT_MODE DDRF
		#define FE_DIGITAL_PIN_A0_PORT_IN PINF
		#define FE_DIGITAL_PIN_A0_PORT_OUT PORTF
		#define FE_DIGITAL_PIN_A0_PORT_NUMBER 5
		#define FE_ANALOG_PIN_A0_MASK B00000111

		#define FE_DIGITAL_PIN_A1_MASK B01000000
		#define FE_DIGITAL_PIN_A1_PORT_MODE DDRF
		#define FE_DIGITAL_PIN_A1_PORT_IN PINF
		#define FE_DIGITAL_PIN_A1_PORT_OUT PORTF
		#define FE_DIGITAL_PIN_A1_PORT_NUMBER 5
		#define FE_ANALOG_PIN_A1_MASK B00000110

		#define FE_DIGITAL_PIN_A2_MASK B00100000
		#define FE_DIGITAL_PIN_A2_PORT_MODE DDRF
		#define FE_DIGITAL_PIN_A2_PORT_IN PINF
		#define FE_DIGITAL_PIN_A2_PORT_OUT PORTF
		#define FE_DIGITAL_PIN_A2_PORT_NUMBER 5
		#define FE_ANALOG_PIN_A2_MASK B00000101

		#define FE_DIGITAL_PIN_A3_MASK B00010000
		#define FE_DIGITAL_PIN_A3_PORT_MODE DDRF
		#define FE_DIGITAL_PIN_A3_PORT_IN PINF
		#define FE_DIGITAL_PIN_A3_PORT_OUT PORTF
		#define FE_DIGITAL_PIN_A3_PORT_NUMBER 5
		#define FE_ANALOG_PIN_A3_MASK B00000100

	#endif
#endif