/*
	ArduinoTiny ports : 
		PORTB :         [D3],        [D4],        [D5],        [D1],        [D2],        [D0],           *,           *
*/

#ifndef ARDUINO_TINY_PINMAP_H
#define ARDUINO_TINY_PINMAP_H

	#if defined(__AVR_ATtiny85__)

		#define FE_DIGITAL_PIN_D0_MASK B00100000
		#define FE_DIGITAL_PIN_D0_PORT_MODE DDRB
		#define FE_DIGITAL_PIN_D0_PORT_IN PINB
		#define FE_DIGITAL_PIN_D0_PORT_OUT PORTB
		#define FE_DIGITAL_PIN_D0_PORT_NUMBER 1

		#define FE_DIGITAL_PIN_D1_MASK B00001000
		#define FE_DIGITAL_PIN_D1_PORT_MODE DDRB
		#define FE_DIGITAL_PIN_D1_PORT_IN PINB
		#define FE_DIGITAL_PIN_D1_PORT_OUT PORTB
		#define FE_DIGITAL_PIN_D1_PORT_NUMBER 1

		#define FE_DIGITAL_PIN_D2_MASK B00010000
		#define FE_DIGITAL_PIN_D2_PORT_MODE DDRB
		#define FE_DIGITAL_PIN_D2_PORT_IN PINB
		#define FE_DIGITAL_PIN_D2_PORT_OUT PORTB
		#define FE_DIGITAL_PIN_D2_PORT_NUMBER 1

		#define FE_DIGITAL_PIN_D3_MASK B00000001
		#define FE_DIGITAL_PIN_D3_PORT_MODE DDRB
		#define FE_DIGITAL_PIN_D3_PORT_IN PINB
		#define FE_DIGITAL_PIN_D3_PORT_OUT PORTB
		#define FE_DIGITAL_PIN_D3_PORT_NUMBER 1

		#define FE_DIGITAL_PIN_D4_MASK B00000010
		#define FE_DIGITAL_PIN_D4_PORT_MODE DDRB
		#define FE_DIGITAL_PIN_D4_PORT_IN PINB
		#define FE_DIGITAL_PIN_D4_PORT_OUT PORTB
		#define FE_DIGITAL_PIN_D4_PORT_NUMBER 1

		#define FE_DIGITAL_PIN_D5_MASK B00000100
		#define FE_DIGITAL_PIN_D5_PORT_MODE DDRB
		#define FE_DIGITAL_PIN_D5_PORT_IN PINB
		#define FE_DIGITAL_PIN_D5_PORT_OUT PORTB
		#define FE_DIGITAL_PIN_D5_PORT_NUMBER 1

	#endif
#endif