/*
	ArduinoNano ports : 
		PORTB :         [D8],        [D9],       [D10],       [D11],       [D12],       [D13],           *,           *
		PORTC :         [A0],        [A1],        [A2],        [A3],        [A4],        [A5],     [RESET],           *
		PORTD :        [RX0],       [TX0],        [D2],        [D3],        [D4],        [D5],        [D6],        [D7]
*/

#ifndef ARDUINO_NANO_PINMAP_H
#define ARDUINO_NANO_PINMAP_H

	#if defined(__AVR_ATmega328P__)

		#define FE_DIGITAL_PIN_D3_MASK B00001000
		#define FE_DIGITAL_PIN_D3_PORT_MODE DDRD
		#define FE_DIGITAL_PIN_D3_PORT_IN PIND
		#define FE_DIGITAL_PIN_D3_PORT_OUT PORTD
		#define FE_DIGITAL_PIN_D3_PORT_NUMBER 3
		#define FE_INTERRUPT_PIN_D3_GROUP_MASK B00000100
		#define FE_INTERRUPT_PIN_D3_GROUP PCMSK2
		#define FE_INTERRUPT_PIN_D3_GROUP_NUMBER 2
		#define FE_INTERRUPT_PIN_D3_MASK B00001000

		#define FE_DIGITAL_PIN_D4_MASK B00010000
		#define FE_DIGITAL_PIN_D4_PORT_MODE DDRD
		#define FE_DIGITAL_PIN_D4_PORT_IN PIND
		#define FE_DIGITAL_PIN_D4_PORT_OUT PORTD
		#define FE_DIGITAL_PIN_D4_PORT_NUMBER 3
		#define FE_INTERRUPT_PIN_D4_GROUP_MASK B00000100
		#define FE_INTERRUPT_PIN_D4_GROUP PCMSK2
		#define FE_INTERRUPT_PIN_D4_GROUP_NUMBER 2
		#define FE_INTERRUPT_PIN_D4_MASK B00010000

		#define FE_DIGITAL_PIN_D5_MASK B00100000
		#define FE_DIGITAL_PIN_D5_PORT_MODE DDRD
		#define FE_DIGITAL_PIN_D5_PORT_IN PIND
		#define FE_DIGITAL_PIN_D5_PORT_OUT PORTD
		#define FE_DIGITAL_PIN_D5_PORT_NUMBER 3
		#define FE_INTERRUPT_PIN_D5_GROUP_MASK B00000100
		#define FE_INTERRUPT_PIN_D5_GROUP PCMSK2
		#define FE_INTERRUPT_PIN_D5_GROUP_NUMBER 2
		#define FE_INTERRUPT_PIN_D5_MASK B00100000

		#define FE_DIGITAL_PIN_D6_MASK B01000000
		#define FE_DIGITAL_PIN_D6_PORT_MODE DDRD
		#define FE_DIGITAL_PIN_D6_PORT_IN PIND
		#define FE_DIGITAL_PIN_D6_PORT_OUT PORTD
		#define FE_DIGITAL_PIN_D6_PORT_NUMBER 3
		#define FE_INTERRUPT_PIN_D6_GROUP_MASK B00000100
		#define FE_INTERRUPT_PIN_D6_GROUP PCMSK2
		#define FE_INTERRUPT_PIN_D6_GROUP_NUMBER 2
		#define FE_INTERRUPT_PIN_D6_MASK B01000000

		#define FE_DIGITAL_PIN_D7_MASK B10000000
		#define FE_DIGITAL_PIN_D7_PORT_MODE DDRD
		#define FE_DIGITAL_PIN_D7_PORT_IN PIND
		#define FE_DIGITAL_PIN_D7_PORT_OUT PORTD
		#define FE_DIGITAL_PIN_D7_PORT_NUMBER 3
		#define FE_INTERRUPT_PIN_D7_GROUP_MASK B00000100
		#define FE_INTERRUPT_PIN_D7_GROUP PCMSK2
		#define FE_INTERRUPT_PIN_D7_GROUP_NUMBER 2
		#define FE_INTERRUPT_PIN_D7_MASK B10000000

		#define FE_DIGITAL_PIN_D8_MASK B00000001
		#define FE_DIGITAL_PIN_D8_PORT_MODE DDRB
		#define FE_DIGITAL_PIN_D8_PORT_IN PINB
		#define FE_DIGITAL_PIN_D8_PORT_OUT PORTB
		#define FE_DIGITAL_PIN_D8_PORT_NUMBER 1
		#define FE_INTERRUPT_PIN_D8_GROUP_MASK B00000001
		#define FE_INTERRUPT_PIN_D8_GROUP PCMSK0
		#define FE_INTERRUPT_PIN_D8_GROUP_NUMBER 0
		#define FE_INTERRUPT_PIN_D8_MASK B00000001

		#define FE_DIGITAL_PIN_D9_MASK B00000010
		#define FE_DIGITAL_PIN_D9_PORT_MODE DDRB
		#define FE_DIGITAL_PIN_D9_PORT_IN PINB
		#define FE_DIGITAL_PIN_D9_PORT_OUT PORTB
		#define FE_DIGITAL_PIN_D9_PORT_NUMBER 1
		#define FE_INTERRUPT_PIN_D9_GROUP_MASK B00000001
		#define FE_INTERRUPT_PIN_D9_GROUP PCMSK0
		#define FE_INTERRUPT_PIN_D9_GROUP_NUMBER 0
		#define FE_INTERRUPT_PIN_D9_MASK B00000010

		#define FE_DIGITAL_PIN_D10_MASK B00000100
		#define FE_DIGITAL_PIN_D10_PORT_MODE DDRB
		#define FE_DIGITAL_PIN_D10_PORT_IN PINB
		#define FE_DIGITAL_PIN_D10_PORT_OUT PORTB
		#define FE_DIGITAL_PIN_D10_PORT_NUMBER 1
		#define FE_INTERRUPT_PIN_D10_GROUP_MASK B00000001
		#define FE_INTERRUPT_PIN_D10_GROUP PCMSK0
		#define FE_INTERRUPT_PIN_D10_GROUP_NUMBER 0
		#define FE_INTERRUPT_PIN_D10_MASK B00000100

		#define FE_DIGITAL_PIN_D11_MASK B00001000
		#define FE_DIGITAL_PIN_D11_PORT_MODE DDRB
		#define FE_DIGITAL_PIN_D11_PORT_IN PINB
		#define FE_DIGITAL_PIN_D11_PORT_OUT PORTB
		#define FE_DIGITAL_PIN_D11_PORT_NUMBER 1
		#define FE_INTERRUPT_PIN_D11_GROUP_MASK B00000001
		#define FE_INTERRUPT_PIN_D11_GROUP PCMSK0
		#define FE_INTERRUPT_PIN_D11_GROUP_NUMBER 0
		#define FE_INTERRUPT_PIN_D11_MASK B00001000

		#define FE_DIGITAL_PIN_D12_MASK B00010000
		#define FE_DIGITAL_PIN_D12_PORT_MODE DDRB
		#define FE_DIGITAL_PIN_D12_PORT_IN PINB
		#define FE_DIGITAL_PIN_D12_PORT_OUT PORTB
		#define FE_DIGITAL_PIN_D12_PORT_NUMBER 1
		#define FE_INTERRUPT_PIN_D12_GROUP_MASK B00000001
		#define FE_INTERRUPT_PIN_D12_GROUP PCMSK0
		#define FE_INTERRUPT_PIN_D12_GROUP_NUMBER 0
		#define FE_INTERRUPT_PIN_D12_MASK B00010000

		#define FE_DIGITAL_PIN_D13_MASK B00100000
		#define FE_DIGITAL_PIN_D13_PORT_MODE DDRB
		#define FE_DIGITAL_PIN_D13_PORT_IN PINB
		#define FE_DIGITAL_PIN_D13_PORT_OUT PORTB
		#define FE_DIGITAL_PIN_D13_PORT_NUMBER 1
		#define FE_INTERRUPT_PIN_D13_GROUP_MASK B00000001
		#define FE_INTERRUPT_PIN_D13_GROUP PCMSK0
		#define FE_INTERRUPT_PIN_D13_GROUP_NUMBER 0
		#define FE_INTERRUPT_PIN_D13_MASK B00100000

		#define FE_ANALOG_PIN_A6_MASK B00000110

		#define FE_ANALOG_PIN_A7_MASK B00000111

		#define FE_DIGITAL_PIN_A0_MASK B00000001
		#define FE_DIGITAL_PIN_A0_PORT_MODE DDRC
		#define FE_DIGITAL_PIN_A0_PORT_IN PINC
		#define FE_DIGITAL_PIN_A0_PORT_OUT PORTC
		#define FE_DIGITAL_PIN_A0_PORT_NUMBER 2
		#define FE_ANALOG_PIN_A0_MASK B00000000
		#define FE_INTERRUPT_PIN_A0_GROUP_MASK B00000010
		#define FE_INTERRUPT_PIN_A0_GROUP PCMSK1
		#define FE_INTERRUPT_PIN_A0_GROUP_NUMBER 1
		#define FE_INTERRUPT_PIN_A0_MASK B00000001

		#define FE_DIGITAL_PIN_A1_MASK B00000010
		#define FE_DIGITAL_PIN_A1_PORT_MODE DDRC
		#define FE_DIGITAL_PIN_A1_PORT_IN PINC
		#define FE_DIGITAL_PIN_A1_PORT_OUT PORTC
		#define FE_DIGITAL_PIN_A1_PORT_NUMBER 2
		#define FE_ANALOG_PIN_A1_MASK B00000001
		#define FE_INTERRUPT_PIN_A1_GROUP_MASK B00000010
		#define FE_INTERRUPT_PIN_A1_GROUP PCMSK1
		#define FE_INTERRUPT_PIN_A1_GROUP_NUMBER 1
		#define FE_INTERRUPT_PIN_A1_MASK B00000010

		#define FE_DIGITAL_PIN_A2_MASK B00000100
		#define FE_DIGITAL_PIN_A2_PORT_MODE DDRC
		#define FE_DIGITAL_PIN_A2_PORT_IN PINC
		#define FE_DIGITAL_PIN_A2_PORT_OUT PORTC
		#define FE_DIGITAL_PIN_A2_PORT_NUMBER 2
		#define FE_ANALOG_PIN_A2_MASK 
		#define FE_INTERRUPT_PIN_A2_GROUP_MASK B00000010
		#define FE_INTERRUPT_PIN_A2_GROUP PCMSK1
		#define FE_INTERRUPT_PIN_A2_GROUP_NUMBER 1
		#define FE_INTERRUPT_PIN_A2_MASK B00000100

		#define FE_DIGITAL_PIN_A3_MASK B00001000
		#define FE_DIGITAL_PIN_A3_PORT_MODE DDRC
		#define FE_DIGITAL_PIN_A3_PORT_IN PINC
		#define FE_DIGITAL_PIN_A3_PORT_OUT PORTC
		#define FE_DIGITAL_PIN_A3_PORT_NUMBER 2
		#define FE_ANALOG_PIN_A3_MASK 
		#define FE_INTERRUPT_PIN_A3_GROUP_MASK B00000010
		#define FE_INTERRUPT_PIN_A3_GROUP PCMSK1
		#define FE_INTERRUPT_PIN_A3_GROUP_NUMBER 1
		#define FE_INTERRUPT_PIN_A3_MASK B00001000

		#define FE_DIGITAL_PIN_A4_MASK B00010000
		#define FE_DIGITAL_PIN_A4_PORT_MODE DDRC
		#define FE_DIGITAL_PIN_A4_PORT_IN PINC
		#define FE_DIGITAL_PIN_A4_PORT_OUT PORTC
		#define FE_DIGITAL_PIN_A4_PORT_NUMBER 2
		#define FE_ANALOG_PIN_A4_MASK B00000100
		#define FE_INTERRUPT_PIN_A4_GROUP_MASK B00000010
		#define FE_INTERRUPT_PIN_A4_GROUP PCMSK1
		#define FE_INTERRUPT_PIN_A4_GROUP_NUMBER 1
		#define FE_INTERRUPT_PIN_A4_MASK B00010000

		#define FE_DIGITAL_PIN_A5_MASK B00100000
		#define FE_DIGITAL_PIN_A5_PORT_MODE DDRC
		#define FE_DIGITAL_PIN_A5_PORT_IN PINC
		#define FE_DIGITAL_PIN_A5_PORT_OUT PORTC
		#define FE_DIGITAL_PIN_A5_PORT_NUMBER 2
		#define FE_ANALOG_PIN_A5_MASK B00000101
		#define FE_INTERRUPT_PIN_A5_GROUP_MASK B00000010
		#define FE_INTERRUPT_PIN_A5_GROUP PCMSK1
		#define FE_INTERRUPT_PIN_A5_GROUP_NUMBER 1
		#define FE_INTERRUPT_PIN_A5_MASK B00100000

		#define FE_DIGITAL_PIN_RESET_MASK B01000000
		#define FE_DIGITAL_PIN_RESET_PORT_MODE DDRC
		#define FE_DIGITAL_PIN_RESET_PORT_IN PINC
		#define FE_DIGITAL_PIN_RESET_PORT_OUT PORTC
		#define FE_DIGITAL_PIN_RESET_PORT_NUMBER 2
		#define FE_INTERRUPT_PIN_RESET_GROUP_MASK B00000010
		#define FE_INTERRUPT_PIN_RESET_GROUP PCMSK1
		#define FE_INTERRUPT_PIN_RESET_GROUP_NUMBER 1
		#define FE_INTERRUPT_PIN_RESET_MASK B01000000

		#define FE_DIGITAL_PIN_RX0_MASK B00000001
		#define FE_DIGITAL_PIN_RX0_PORT_MODE DDRD
		#define FE_DIGITAL_PIN_RX0_PORT_IN PIND
		#define FE_DIGITAL_PIN_RX0_PORT_OUT PORTD
		#define FE_DIGITAL_PIN_RX0_PORT_NUMBER 3
		#define FE_INTERRUPT_PIN_RX0_GROUP_MASK B00000100
		#define FE_INTERRUPT_PIN_RX0_GROUP PCMSK2
		#define FE_INTERRUPT_PIN_RX0_GROUP_NUMBER 2
		#define FE_INTERRUPT_PIN_RX0_MASK B00000001

		#define FE_DIGITAL_PIN_TX0_MASK B00000010
		#define FE_DIGITAL_PIN_TX0_PORT_MODE DDRD
		#define FE_DIGITAL_PIN_TX0_PORT_IN PIND
		#define FE_DIGITAL_PIN_TX0_PORT_OUT PORTD
		#define FE_DIGITAL_PIN_TX0_PORT_NUMBER 3
		#define FE_INTERRUPT_PIN_TX0_GROUP_MASK B00000100
		#define FE_INTERRUPT_PIN_TX0_GROUP PCMSK2
		#define FE_INTERRUPT_PIN_TX0_GROUP_NUMBER 2
		#define FE_INTERRUPT_PIN_TX0_MASK B00000010

		#define FE_DIGITAL_PIN_D2_MASK B00000100
		#define FE_DIGITAL_PIN_D2_PORT_MODE DDRD
		#define FE_DIGITAL_PIN_D2_PORT_IN PIND
		#define FE_DIGITAL_PIN_D2_PORT_OUT PORTD
		#define FE_DIGITAL_PIN_D2_PORT_NUMBER 3
		#define FE_INTERRUPT_PIN_D2_GROUP_MASK B00000100
		#define FE_INTERRUPT_PIN_D2_GROUP PCMSK2
		#define FE_INTERRUPT_PIN_D2_GROUP_NUMBER 2
		#define FE_INTERRUPT_PIN_D2_MASK B00000100

	#endif
#endif